// Copyright Â© 2018, Meta Company.  All rights reserved.
// 
// Redistribution and use of this software (the "Software") in binary form, without modification, is 
// permitted provided that the following conditions are met:
// 
// 1.      Redistributions of the unmodified Software in binary form must reproduce the above 
//         copyright notice, this list of conditions and the following disclaimer in the 
//         documentation and/or other materials provided with the distribution.
// 2.      The name of Meta Company (â€œMetaâ€) may not be used to endorse or promote products derived 
//         from this Software without specific prior written permission from Meta.
// 3.      LIMITATION TO META PLATFORM: Use of the Software is limited to use on or in connection 
//         with Meta-branded devices or Meta-branded software development kits.  For example, a bona 
//         fide recipient of the Software may incorporate an unmodified binary version of the 
//         Software into an application limited to use on or in connection with a Meta-branded 
//         device, while he or she may not incorporate an unmodified binary version of the Software 
//         into an application designed or offered for use on a non-Meta-branded device.
// 
// For the sake of clarity, the Software may not be redistributed under any circumstances in source 
// code form, or in the form of modified binary code â€“ and nothing in this License shall be construed 
// to permit such redistribution.
// 
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, 
// INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A 
// PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL META COMPANY BE LIABLE FOR ANY DIRECT, 
// INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, 
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA OR PROFITS; OR BUSINESS 
// INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT 
// LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS 
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace meta.types
{

using global::System;
using global::FlatBuffers;

public struct FrameHands : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static FrameHands GetRootAsFrameHands(ByteBuffer _bb) { return GetRootAsFrameHands(_bb, new FrameHands()); }
  public static FrameHands GetRootAsFrameHands(ByteBuffer _bb, FrameHands obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public FrameHands __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public meta.types.BufferHeader? Header { get { int o = __p.__offset(4); return o != 0 ? (meta.types.BufferHeader?)(new meta.types.BufferHeader()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public int HandCount { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public meta.types.HandData? Hands(int j) { int o = __p.__offset(8); return o != 0 ? (meta.types.HandData?)(new meta.types.HandData()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int HandsLength { get { int o = __p.__offset(8); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<FrameHands> CreateFrameHands(FlatBufferBuilder builder,
      Offset<meta.types.BufferHeader> headerOffset = default(Offset<meta.types.BufferHeader>),
      int hand_count = 0,
      VectorOffset handsOffset = default(VectorOffset)) {
    builder.StartObject(3);
    FrameHands.AddHands(builder, handsOffset);
    FrameHands.AddHandCount(builder, hand_count);
    FrameHands.AddHeader(builder, headerOffset);
    return FrameHands.EndFrameHands(builder);
  }

  public static void StartFrameHands(FlatBufferBuilder builder) { builder.StartObject(3); }
  public static void AddHeader(FlatBufferBuilder builder, Offset<meta.types.BufferHeader> headerOffset) { builder.AddOffset(0, headerOffset.Value, 0); }
  public static void AddHandCount(FlatBufferBuilder builder, int handCount) { builder.AddInt(1, handCount, 0); }
  public static void AddHands(FlatBufferBuilder builder, VectorOffset handsOffset) { builder.AddOffset(2, handsOffset.Value, 0); }
  public static VectorOffset CreateHandsVector(FlatBufferBuilder builder, Offset<meta.types.HandData>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static void StartHandsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<FrameHands> EndFrameHands(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<FrameHands>(o);
  }
  public static void FinishFrameHandsBuffer(FlatBufferBuilder builder, Offset<FrameHands> offset) { builder.Finish(offset.Value); }
};


}
